token = "put Token API of your Telegram Bot here"
command_start = "Start info of your Bot!"
command_settings = "Settings of your Bot"
command_help = "Help info about your Bot"
answer_default = "I am a your InfoBot!"
answer_hi = "Hi user!"
answer_bye = "Bye-bye!"